export const path = {
  CLIENT: {
    DEFAULT: "/",
    HOME_PAGE: "/home",
    ABOUT_PAGE: "/about",
    PROFILE: "/profile/:id",
    LOGIN: "/login",
    GENERATE: "/generate",
    RECEIVE: "/receive/:id",
    SIGNUP: "/signup"
  },
  API: {
    PROFILE: "/profile",
    NOTIFICATION: "/notification",
    POST: "/posts",
    USER: "/users",
    PHOTOS: "/photos",
    LOGIN: "/v1/auth/login",
    SIGNUP: "/v1/auth/register",
    ENVELOPES: "/v1/envelopes",
    ENVELOPES_CREATE: "/v1/envelopes/create",
    ENVELOPES_RECEIVE: "/v1/envelopes/receive",
  },
};

export const BANK = [
  { value: "momo", label: "Momo" },
  { value: "bidv", label: "BIDV" },
  { value: "vietcombank", label: "Vietcombank" },
  { value: "techcombank", label: "Techcombank" },
  { value: "vietinbank", label: "VietinBank" },
  { value: "agribank", label: "Agribank" },
  { value: "sacombank", label: "Sacombank" },
  { value: "vpbank", label: "VPBank" },
  { value: "acb", label: "ACB" },
  { value: "mbbank", label: "MBBank" },
  { value: "eximbank", label: "Eximbank" },
  { value: "shb", label: "SHB" },
  { value: "vib", label: "VIB" },
  { value: "abbank", label: "ABBank" },
  { value: "seabank", label: "SeaBank" },
  { value: "hdbank", label: "HDBank" },
  { value: "namabank", label: "NamABank" },
  { value: "tpbank", label: "TPBank" },
  { value: "kienlongbank", label: "KienLongBank" },
  { value: "baovietbank", label: "BaoVietBank" },
  { value: "pvcombank", label: "PVcomBank" },
  { value: "gpbank", label: "GPBank" },
  { value: "ocb", label: "OCB" },
  { value: "bvb", label: "BVB" },
  { value: "navibank", label: "Navibank" },
  { value: "vietabank", label: "VietABank" },
  { value: "vrb", label: "VRB" },
  { value: "bacabank", label: "BacABank" },
  { value: "lienvietpostbank", label: "LienvietPostBank" },
  { value: "pgbank", label: "PGBank" },
  { value: "tpbank", label: "TPBank" },
  { value: "vietbank", label: "VietBank" },
  { value: "dongabank", label: "DongABank" },
  { value: "mb", label: "MB" },
  { value: "saigonbank", label: "SaigonBank" },
  { value: "shb", label: "SHB" },
  { value: "seabank", label: "SeaBank" },
  { value: "lienvietbank", label: "LienVietBank" },
  { value: "vpbank", label: "VPBank" },
  { value: "vietcapitalbank", label: "VietCapitalBank" },
  { value: "pvbank", label: "PVBank" },
  { value: "msb", label: "MSB" },
];